CREATE TABLE IF NOT EXISTS events (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  eventDate DATETIME(3) NOT NULL,
  location VARCHAR(255) NOT NULL,
  message TEXT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);

CREATE TABLE IF NOT EXISTS guests (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  eventId INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  contact VARCHAR(255) NULL,
  token VARCHAR(255) NOT NULL UNIQUE,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  INDEX guests_eventId_idx (eventId),
  CONSTRAINT guests_eventId_fkey FOREIGN KEY (eventId) REFERENCES events(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS rsvps (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  guestId INT NOT NULL UNIQUE,
  status ENUM('YES', 'NO') NOT NULL,
  companions INT NOT NULL DEFAULT 0,
  comment TEXT NULL,
  respondedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  INDEX rsvps_status_idx (status),
  CONSTRAINT rsvps_guestId_fkey FOREIGN KEY (guestId) REFERENCES guests(id) ON DELETE CASCADE ON UPDATE CASCADE
);
